name: iNations
author: Chiori Greene
main: com.chiorichan.bukkit.plugin.iNations.INations
version: '0.1'
depends: [Vault]

commands:
     iplayer:
          description: iNations Command Subroutine for Players.
          usage: /iplayer <subcommand>
     iadmin:
          description: iNations Command Subroutine for Admins.
          usage: /iadmin <subcommand>
     inv:
          description: Allows viewing of anothers players inventory.
          usage: /inv <playername>
     clear:
          description: Allows for instant clear of inventory.
          usage: /clear [h/i]
     t:
          description: Allows for private chat for staff even when hidden. Alt Colors Supported.
          usage: /t <playersname> <message>
     goto:
          description: Allows you to teleport to players. Gives OP's a warning of teleport.
          usage: /goto <playersname>